### ISSUE TITLE
Suggestions: Ability to hide/Mask account name and password protect infront of logins?

### ISSUE THREAD

**Issue by wazerstar** [nombersDev/casemove#101]
2 Suggestions

Hi as streamers, I would like to be able to hide account names below alias before you click login, I guess this can be easily made?

Also be able to have a password in front during startup of program to avoid somebody gaining access rather easy when you save login information in the program, where it also is encrypted, what do you think

Would those 2 requests be pretty straight forward to do and bring some better/basic security?

**Comment by kzrk1ng** [comment]
Thought I'd add on to this rather than make my own thread; I think the selection interface is a little unintuitive.
I know the primary purpsoe of this program is to facilitate mass inventory management of single items, but I naturally headed to Casemove because I wanted to transfer a decent chunk of low value items between storage units, but it seemed like trying to individually select lots of items was actually quite difficult in that the icon was quite small. Repeat this over a few hundred items, and I'm suddenly thinking doing this in-game would be far easier.

On that note, I ended up second-guessing myself a few times in regards to what items I had actually selected. Although the lightning bolt and x icons are different, I feel like something as simple as just colouring in the lightning bolt would be far more intuitive than two greyscale icons, one of which is niche/ambiguous.

My personal opinion is that the entire 'banner' of each individual item should be completely selectable, and the banner should change colour upon selection for visual clarity. I think when we are talking about a program that is designed for mass transfer of items, visual clarity and ease of use are imperative.

Hope the suggestion provides some insight,
k1
